name: 'Sphinx-Doxygen'
description: 'Building out sphinx docs with Doxygen integration'
branding:
  icon: 'book-open'
  color: 'gray-dark'
inputs:
  sphinx-path:
    description: 'Path to sphinx _build folder'
    required: true
    default: './_build'
  doxyfile-path:
    description: 'Path to Doxyfile'
    required: true
    default: './Doxyfile'
  working-directory:
    description: 'Working directory'
    required: true
    default: '.'
  enable-latex:
    description: 'Generate latex documentation'
    required: false
    default: 'false'
  additional-packages:
    description: 'Extra alpine packages for the build environment'
    required: false
    default: 'sphinx'

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.doxyfile-path }}
    - ${{ inputs.working-directory }}
    - ${{ inputs.enable-latex }}
    - ${{ inputs.additional-packages }}
    - ${{ inputs.sphinx-path }}
